using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VRCVideoCacher.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class SingletonGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly DiagnosticDescriptor MemberNameTooShortRule = new(
        id: "VVC0001",
        title: "Singleton member name is too short for static proxy generation",
        messageFormat: "Member '{0}' in singleton '{1}' cannot generate a static proxy because its name has only {2} character(s) (must have at least 2 characters to trim the last character)",
        category: "SingletonGenerator",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Query target classes that inherit from Singleton<T>
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, cancellationToken) => IsSyntaxTargetForGeneration(s, cancellationToken),
                transform: static (ctx, ct) => GetSemanticTargetForGeneration(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (item, _) => item!.Value);

        var distinctClasses = classDeclarations
            .Collect()
            .SelectMany(static (items, _) => items.Distinct());

        // 2. Register source output
        context.RegisterSourceOutput(distinctClasses,
            static (spc, target) =>
            {
                foreach (var diagnostic in target.Diagnostics)
                {
                    spc.ReportDiagnostic(diagnostic);
                }

                if (!string.IsNullOrEmpty(target.SourceText))
                {
                    spc.AddSource(target.HintName, SourceText.From(target.SourceText, Encoding.UTF8));
                }
            });
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken cancellationToken) =>
        node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };

    private static TargetClassInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken);
        if (symbol is not { TypeKind: TypeKind.Class })
            return null;

        if (!InheritsFromSingleton(symbol))
            return null;

        return GenerateClassCode(symbol);
    }

    private static bool InheritsFromSingleton(INamedTypeSymbol? symbol)
    {
        var current = symbol?.BaseType;
        while (current != null)
        {
            if (current.Name == "Singleton" &&
                current.ContainingNamespace?.ToDisplayString() == "VRCVideoCacher.Utils")
                return true;

            current = current.BaseType;
        }

        return false;
    }

    private static TargetClassInfo GenerateClassCode(INamedTypeSymbol symbol)
    {
        var fullDisplay = symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        var safeHintName = fullDisplay
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(' ', '_')
            .Replace(',', '_');

        var hintName = $"{safeHintName}.SingletonGenerated.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Assembly-level SuppressMessage attributes
        var fullMetadataOrDocCommentName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "");
        var targetDocId = symbol.GetDocumentationCommentId() ?? $"T:{fullMetadataOrDocCommentName}";
        // Ensure format starts with ~T:
        var targetSpec = targetDocId.StartsWith("T:") ? $"~{targetDocId}" : $"~T:{fullMetadataOrDocCommentName}";

        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Global\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Local\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBePrivate.Global\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBePrivate.Local\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine();

        // Class configuration
        var (enabled, prefix, suffix) = GetClassProxyConfig(symbol);

        var ns = symbol.ContainingNamespace;
        var hasNamespace = ns is { IsGlobalNamespace: false };
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {ns!.ToDisplayString()}");
            sb.AppendLine("{");
        }

        var containingTypes = new List<INamedTypeSymbol>();
        var outer = symbol.ContainingType;
        while (outer != null)
        {
            containingTypes.Insert(0, outer);
            outer = outer.ContainingType;
        }

        var indent = hasNamespace ? "    " : "";
        foreach (var outerType in containingTypes)
        {
            sb.AppendLine($"{indent}sealed partial class {GetTypeDeclaration(outerType)}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // Partial class definition with static proxies
        sb.AppendLine($"{indent}sealed partial class {GetTypeDeclaration(symbol)}");
        sb.AppendLine($"{indent}{{");

        var diagnostics = new List<Diagnostic>();
        if (enabled)
            GenerateStaticMembers(sb, indent + "    ", symbol, prefix, suffix, diagnostics);

        sb.AppendLine($"{indent}}}");

        for (var i = 0; i < containingTypes.Count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
            sb.AppendLine("}");

        return new(hintName, sb.ToString(), diagnostics);
    }

    private static (bool Enabled, string Prefix, string Suffix) GetClassProxyConfig(INamedTypeSymbol symbol)
    {
        var enabled = true;
        var prefix = "";
        var suffix = "";

        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.Name is "SingletonStaticProxyAttribute" or "SingletonStaticProxy")
                foreach (var namedArg in attr.NamedArguments)
                    switch (namedArg)
                    {
                        case { Key: "Enabled", Value.Value: bool b }:
                            enabled = b;
                            break;
                        case { Key: "Prefix", Value.Value: string p }:
                            prefix = p;
                            break;
                        case { Key: "Suffix", Value.Value: string s }:
                            suffix = s;
                            break;
                    }

        return (enabled, prefix, suffix);
    }

    private static void GenerateStaticMembers(StringBuilder sb, string indent, INamedTypeSymbol symbol, string prefix,
        string suffix, List<Diagnostic> diagnostics)
    {
        var members = symbol.GetMembers();

        foreach (var member in members)
        {
            if (member.IsStatic)
                continue;

            var isPublic = member.DeclaredAccessibility == Accessibility.Public;
            var isExplicitlyIncluded = HasAttribute(member, "StaticIncludeAttribute", "StaticInclude") ||
                                       HasAttribute(member, "StaticTrimLastAttribute", "StaticTrimLast") ||
                                       HasAttribute(member, "StaticTrimEndAttribute", "StaticTrimEnd") ||
                                       HasAttribute(member, "StaticDropLastAttribute", "StaticDropLast");

            if (!isPublic && !isExplicitlyIncluded)
                continue;

            // Check if ignored
            if (HasAttribute(member, "StaticIgnoreAttribute", "StaticIgnore"))
                continue;

            // Determine if the member is a valid candidate for proxy generation
            switch (member)
            {
                case IPropertySymbol { IsIndexer: true }:
                    continue;
                case IPropertySymbol:
                case IFieldSymbol:
                case IMethodSymbol method when method.MethodKind == MethodKind.Ordinary && method.ContainingType.SpecialType != SpecialType.System_Object:
                case IEventSymbol:
                    break;
                default:
                    continue;
            }

            var customName = GetExplicitCustomName(member);
            string staticName;

            if (customName != null)
            {
                staticName = customName;
            }
            else
            {
                if (member.Name.Length <= 1)
                {
                    var location = member.Locations.FirstOrDefault() ?? Location.None;
                    diagnostics.Add(Diagnostic.Create(MemberNameTooShortRule, location, member.Name, symbol.Name, member.Name.Length));
                    continue;
                }

                var baseName = member.Name.Substring(0, member.Name.Length - 1);
                staticName = $"{prefix}{baseName}{suffix}";
            }

            switch (member)
            {
                case IPropertySymbol prop:
                {
                    var hasGet = prop.GetMethod != null;
                    var hasSet = prop.SetMethod != null;
                    var canGet = hasGet && (isExplicitlyIncluded ||
                                            prop.GetMethod!.DeclaredAccessibility == Accessibility.Public);
                    var canSet = hasSet && (isExplicitlyIncluded ||
                                            prop.SetMethod!.DeclaredAccessibility == Accessibility.Public);

                    if (!canGet && !canSet)
                        continue;

                    var typeStr = prop.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{prop.Name}\"/></summary>");
                    sb.AppendLine($"{indent}public static {typeStr} {staticName}");
                    sb.AppendLine($"{indent}{{");
                    if (canGet)
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    get => Instance.{prop.Name};");
                    }

                    if (canSet)
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    set => Instance.{prop.Name} = value;");
                    }

                    sb.AppendLine($"{indent}}}");
                    break;
                }
                case IFieldSymbol field:
                {
                    var typeStr = field.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{field.Name}\"/></summary>");
                    if (field.IsReadOnly)
                        sb.AppendLine($"{indent}public static {typeStr} {staticName} => Instance.{field.Name};");
                    else
                    {
                        sb.AppendLine($"{indent}public static {typeStr} {staticName}");
                        sb.AppendLine($"{indent}{{");
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    get => Instance.{field.Name};");
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    set => Instance.{field.Name} = value;");
                        sb.AppendLine($"{indent}}}");
                    }

                    break;
                }
                case IMethodSymbol method:
                {
                    var returnTypeStr = method.ReturnType.ToDisplayString(TypeDisplayFormat);
                    var typeParamsStr = method.TypeParameters.Length > 0
                        ? $"<{string.Join(", ", method.TypeParameters.Select(p => p.Name))}>"
                        : "";

                    var typeParamConstraints = new List<string>();
                    foreach (var tp in method.TypeParameters)
                    {
                        var constraints = new List<string>();
                        if (tp.HasReferenceTypeConstraint) constraints.Add("class");
                        if (tp.HasValueTypeConstraint) constraints.Add("struct");
                        if (tp.HasNotNullConstraint) constraints.Add("notnull");
                        if (tp.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
                        constraints.AddRange(tp.ConstraintTypes.Select(ct => ct.ToDisplayString(TypeDisplayFormat)));
                        if (tp.HasConstructorConstraint) constraints.Add("new()");

                        if (constraints.Count > 0)
                            typeParamConstraints.Add($"where {tp.Name} : {string.Join(", ", constraints)}");
                    }

                    var constraintStr = typeParamConstraints.Count > 0
                        ? " " + string.Join(" ", typeParamConstraints)
                        : "";

                    var paramList = new List<string>();
                    var callArgs = new List<string>();

                    foreach (var p in method.Parameters)
                    {
                        var refPrefix = "";
                        var callRefPrefix = "";
                        switch (p.RefKind)
                        {
                            case RefKind.Ref:
                                refPrefix = "ref ";
                                callRefPrefix = "ref ";
                                break;
                            case RefKind.Out:
                                refPrefix = "out ";
                                callRefPrefix = "out ";
                                break;
                            case RefKind.In:
                                refPrefix = "in ";
                                callRefPrefix = "in ";
                                break;
                            case RefKind.RefReadOnlyParameter:
                                refPrefix = "ref readonly ";
                                callRefPrefix = "in ";
                                break;
                        }

                        var isParams = p.IsParams ? "params " : "";
                        var pType = p.Type.ToDisplayString(TypeDisplayFormat);
                        var pName = EscapeIdentifier(p.Name);
                        var defaultVal = p.HasExplicitDefaultValue
                            ? $" = {FormatDefaultValue(p.ExplicitDefaultValue)}"
                            : "";

                        paramList.Add($"{isParams}{refPrefix}{pType} {pName}{defaultVal}");
                        callArgs.Add($"{callRefPrefix}{pName}");
                    }

                    var paramsStr = string.Join(", ", paramList);
                    var callArgsStr = string.Join(", ", callArgs);

                    var methodTypeArgsStr = method.TypeParameters.Length > 0
                        ? $"<{string.Join(", ", method.TypeParameters.Select(p => p.Name))}>"
                        : "";

                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{method.Name}\"/></summary>");
                    sb.AppendLine(
                        $"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine(
                        method.ReturnsVoid
                            ? $"{indent}public static void {staticName}{typeParamsStr}({paramsStr}){constraintStr} => Instance.{method.Name}{methodTypeArgsStr}({callArgsStr});"
                            : $"{indent}public static {returnTypeStr} {staticName}{typeParamsStr}({paramsStr}){constraintStr} => Instance.{method.Name}{methodTypeArgsStr}({callArgsStr});");
                    break;
                }
                case IEventSymbol evt:
                {
                    var hasAdd = evt.AddMethod != null;
                    var hasRemove = evt.RemoveMethod != null;
                    var canAdd = hasAdd && (isExplicitlyIncluded ||
                                            evt.AddMethod!.DeclaredAccessibility == Accessibility.Public);
                    var canRemove = hasRemove && (isExplicitlyIncluded ||
                                                  evt.RemoveMethod!.DeclaredAccessibility == Accessibility.Public);

                    if (!canAdd && !canRemove)
                        continue;

                    var typeStr = evt.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for event <see cref=\"{evt.Name}\"/></summary>");
                    sb.AppendLine($"{indent}public static event {typeStr} {staticName}");
                    sb.AppendLine($"{indent}{{");
                    if (canAdd)
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    add => Instance.{evt.Name} += value;");
                    }

                    if (canRemove)
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    remove => Instance.{evt.Name} -= value;");
                    }

                    sb.AppendLine($"{indent}}}");
                    break;
                }
            }
        }
    }

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.IsKeywordKind(SyntaxFacts.GetKeywordKind(name)) ? "@" + name : name;

    private static string FormatDefaultValue(object? value)
    {
        return value switch
        {
            null => "default",
            bool b => b ? "true" : "false",
            string s => $"\"{s.Replace("\"", "\\\"")}\"",
            char c => $"'{c}'",
            float f => $"{f}f",
            double d => $"{d}d",
            decimal m => $"{m}m",
            _ => value.ToString()
        };
    }

    private static bool HasAttribute(ISymbol symbol, string attrName1, string attrName2)
    {
        return Enumerable.Any(symbol.GetAttributes(),
            attr => attr.AttributeClass?.Name == attrName1 || attr.AttributeClass?.Name == attrName2);
    }

    private static string? GetExplicitCustomName(ISymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            var attrName = attr.AttributeClass?.Name;
            if (attrName is "StaticIncludeAttribute" or "StaticInclude")
            {
                if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s1 &&
                    !string.IsNullOrEmpty(s1))
                    return s1;

                foreach (var namedArg in attr.NamedArguments)
                {
                    if (namedArg is { Key: "Name", Value.Value: string s2 } && !string.IsNullOrEmpty(s2))
                        return s2;
                }
            }
        }

        return null;
    }

    private static string GetTypeDeclaration(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
            return symbol.Name;

        var typeParams = string.Join(", ", symbol.TypeParameters.Select(static p => p.Name));
        return $"{symbol.Name}<{typeParams}>";
    }

    private readonly struct TargetClassInfo : IEquatable<TargetClassInfo>
    {
        public string HintName { get; }
        public string SourceText { get; }
        public IReadOnlyList<Diagnostic> Diagnostics { get; }

        public TargetClassInfo(string hintName, string sourceText, IReadOnlyList<Diagnostic> diagnostics)
        {
            HintName = hintName;
            SourceText = sourceText;
            Diagnostics = diagnostics;
        }

        public bool Equals(TargetClassInfo other)
        {
            if (HintName != other.HintName || SourceText != other.SourceText)
                return false;

            if (Diagnostics.Count != other.Diagnostics.Count)
                return false;

            for (var i = 0; i < Diagnostics.Count; i++)
            {
                if (!Diagnostics[i].Equals(other.Diagnostics[i]))
                    return false;
            }

            return true;
        }

        public override bool Equals(object? obj) => obj is TargetClassInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = HintName.GetHashCode() * 397 ^ SourceText.GetHashCode();
                foreach (var d in Diagnostics)
                {
                    hash = hash * 31 ^ d.GetHashCode();
                }
                return hash;
            }
        }
    }
}
