using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VRCVideoCacher.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class SingletonSuppressionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s, _),
                transform: static (ctx, ct) => GetSemanticTargetForGeneration(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (item, _) => item!.Value);

        var distinctClasses = classDeclarations
            .Collect()
            .SelectMany(static (items, _) => items.Distinct());

        context.RegisterSourceOutput(distinctClasses, static (spc, target) =>
        {
            spc.AddSource(target.HintName, SourceText.From(target.SourceText, Encoding.UTF8));
        });
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken cancellationToken)
    {
        return node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static TargetClassInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken) as INamedTypeSymbol;
        if (symbol == null || symbol.TypeKind != TypeKind.Class)
            return null;

        if (!InheritsFromSingleton(symbol))
            return null;

        return CreateTargetClassInfo(symbol);
    }

    private static bool InheritsFromSingleton(INamedTypeSymbol? symbol)
    {
        var current = symbol?.BaseType;
        while (current != null)
        {
            if (current.Name == "Singleton" &&
                current.ContainingNamespace?.ToDisplayString() == "VRCVideoCacher.Utils")
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static TargetClassInfo CreateTargetClassInfo(INamedTypeSymbol symbol)
    {
        var fullDisplay = symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        var safeHintName = fullDisplay
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(' ', '_')
            .Replace(',', '_');

        var hintName = $"{safeHintName}.SingletonSuppressions.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var ns = symbol.ContainingNamespace;
        var hasNamespace = ns != null && !ns.IsGlobalNamespace;
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {ns!.ToDisplayString()}");
            sb.AppendLine("{");
        }

        var containingTypes = new List<INamedTypeSymbol>();
        var outer = symbol.ContainingType;
        while (outer != null)
        {
            containingTypes.Insert(0, outer);
            outer = outer.ContainingType;
        }

        var indent = hasNamespace ? "    " : "";
        foreach (var outerType in containingTypes)
        {
            sb.AppendLine($"{indent}partial class {GetTypeDeclaration(outerType)}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Global\")]");
        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Local\")]");
        sb.AppendLine($"{indent}[global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822\")]");
        sb.AppendLine($"{indent}partial class {GetTypeDeclaration(symbol)}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}}}");

        for (var i = 0; i < containingTypes.Count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return new TargetClassInfo(hintName, sb.ToString());
    }

    private static string GetTypeDeclaration(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
            return symbol.Name;

        var typeParams = string.Join(", ", symbol.TypeParameters.Select(static p => p.Name));
        return $"{symbol.Name}<{typeParams}>";
    }

    private readonly struct TargetClassInfo : IEquatable<TargetClassInfo>
    {
        public string HintName { get; }
        public string SourceText { get; }

        public TargetClassInfo(string hintName, string sourceText)
        {
            HintName = hintName;
            SourceText = sourceText;
        }

        public bool Equals(TargetClassInfo other)
        {
            return HintName == other.HintName && SourceText == other.SourceText;
        }

        public override bool Equals(object? obj)
        {
            return obj is TargetClassInfo other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return (HintName.GetHashCode() * 397) ^ SourceText.GetHashCode();
            }
        }
    }
}
