using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VRCVideoCacher.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class SingletonGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Query target classes that inherit from Singleton<T>
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsSyntaxTargetForGeneration(s, _),
                static (ctx, ct) => GetSemanticTargetForGeneration(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (item, _) => item!.Value);

        var distinctClasses = classDeclarations
            .Collect()
            .SelectMany(static (items, _) => items.Distinct());

        // 2. Register source output
        context.RegisterSourceOutput(distinctClasses,
            static (spc, target) =>
            {
                spc.AddSource(target.HintName, SourceText.From(target.SourceText, Encoding.UTF8));
            });
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node, CancellationToken cancellationToken) =>
        node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };

    private static TargetClassInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl, cancellationToken);
        if (symbol is not { TypeKind: TypeKind.Class })
            return null;

        if (!InheritsFromSingleton(symbol))
            return null;

        return GenerateClassCode(symbol);
    }

    private static bool InheritsFromSingleton(INamedTypeSymbol? symbol)
    {
        var current = symbol?.BaseType;
        while (current != null)
        {
            if (current.Name == "Singleton" &&
                current.ContainingNamespace?.ToDisplayString() == "VRCVideoCacher.Utils")
                return true;

            current = current.BaseType;
        }

        return false;
    }

    private static TargetClassInfo GenerateClassCode(INamedTypeSymbol symbol)
    {
        var fullDisplay = symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        var safeHintName = fullDisplay
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(' ', '_')
            .Replace(',', '_');

        var hintName = $"{safeHintName}.SingletonGenerated.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Assembly-level SuppressMessage attributes
        var fullMetadataOrDocCommentName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "");
        var targetDocId = symbol.GetDocumentationCommentId() ?? $"T:{fullMetadataOrDocCommentName}";
        // Ensure format starts with ~T:
        var targetSpec = targetDocId.StartsWith("T:") ? $"~{targetDocId}" : $"~T:{fullMetadataOrDocCommentName}";

        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"Performance\", \"CA1822\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Global\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine(
            $"[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage(\"ReSharper\", \"MemberCanBeMadeStatic.Local\", Scope = \"type\", Target = \"{targetSpec}\")]");
        sb.AppendLine();

        // Class configuration
        var (enabled, prefix, suffix) = GetClassProxyConfig(symbol);

        var ns = symbol.ContainingNamespace;
        var hasNamespace = ns is { IsGlobalNamespace: false };
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {ns!.ToDisplayString()}");
            sb.AppendLine("{");
        }

        var containingTypes = new List<INamedTypeSymbol>();
        var outer = symbol.ContainingType;
        while (outer != null)
        {
            containingTypes.Insert(0, outer);
            outer = outer.ContainingType;
        }

        var indent = hasNamespace ? "    " : "";
        foreach (var outerType in containingTypes)
        {
            sb.AppendLine($"{indent}partial sealed class {GetTypeDeclaration(outerType)}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // Partial class definition with static proxies
        sb.AppendLine($"{indent}partial sealed class {GetTypeDeclaration(symbol)}");
        sb.AppendLine($"{indent}{{");

        if (enabled)
            GenerateStaticMembers(sb, indent + "    ", symbol, prefix, suffix);

        sb.AppendLine($"{indent}}}");

        for (var i = 0; i < containingTypes.Count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
            sb.AppendLine("}");

        return new(hintName, sb.ToString());
    }

    private static (bool Enabled, string Prefix, string Suffix) GetClassProxyConfig(INamedTypeSymbol symbol)
    {
        var enabled = true;
        var prefix = "";
        var suffix = "S";

        foreach (var attr in symbol.GetAttributes())
            if (attr.AttributeClass?.Name is "SingletonStaticProxyAttribute" or "SingletonStaticProxy")
                foreach (var namedArg in attr.NamedArguments)
                    if (namedArg is { Key: "Enabled", Value.Value: bool b })
                        enabled = b;
                    else if (namedArg is { Key: "Prefix", Value.Value: string p })
                        prefix = p;
                    else if (namedArg is { Key: "Suffix", Value.Value: string s })
                        suffix = s;

        return (enabled, prefix, suffix);
    }

    private static void GenerateStaticMembers(StringBuilder sb, string indent, INamedTypeSymbol symbol, string prefix,
        string suffix)
    {
        var members = symbol.GetMembers();
        var generatedCount = 0;

        foreach (var member in members)
        {
            if (member.IsStatic || member.DeclaredAccessibility != Accessibility.Public)
                continue;

            // Check if ignored
            if (HasAttribute(member, "StaticIgnoreAttribute", "StaticIgnore"))
                continue;

            var customName = GetCustomMemberName(member);
            var staticName = customName ?? $"{prefix}{member.Name}{suffix}";

            switch (member)
            {
                case IPropertySymbol { IsIndexer: true }:
                    continue; // Skip indexers
                case IPropertySymbol prop:
                {
                    var typeStr = prop.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{prop.Name}\"/></summary>");
                    sb.AppendLine($"{indent}public static {typeStr} {staticName}");
                    sb.AppendLine($"{indent}{{");
                    if (prop.GetMethod is { DeclaredAccessibility: Accessibility.Public })
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    get => Instance.{prop.Name};");
                    }

                    if (prop.SetMethod is { DeclaredAccessibility: Accessibility.Public })
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    set => Instance.{prop.Name} = value;");
                    }

                    sb.AppendLine($"{indent}}}");
                    generatedCount++;
                    break;
                }
                case IFieldSymbol field:
                {
                    var typeStr = field.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{field.Name}\"/></summary>");
                    if (field.IsReadOnly)
                        sb.AppendLine($"{indent}public static {typeStr} {staticName} => Instance.{field.Name};");
                    else
                    {
                        sb.AppendLine($"{indent}public static {typeStr} {staticName}");
                        sb.AppendLine($"{indent}{{");
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    get => Instance.{field.Name};");
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    set => Instance.{field.Name} = value;");
                        sb.AppendLine($"{indent}}}");
                    }

                    generatedCount++;
                    break;
                }
                case IMethodSymbol method when method.MethodKind != MethodKind.Ordinary:
                    continue;
                // Avoid proxying object methods if any
                case IMethodSymbol method when method.ContainingType.SpecialType == SpecialType.System_Object:
                    continue;
                case IMethodSymbol method:
                {
                    var returnTypeStr = method.ReturnType.ToDisplayString(TypeDisplayFormat);
                    var typeParamsStr = method.TypeParameters.Length > 0
                        ? $"<{string.Join(", ", method.TypeParameters.Select(p => p.Name))}>"
                        : "";

                    var typeParamConstraints = new List<string>();
                    foreach (var tp in method.TypeParameters)
                    {
                        var constraints = new List<string>();
                        if (tp.HasReferenceTypeConstraint) constraints.Add("class");
                        if (tp.HasValueTypeConstraint) constraints.Add("struct");
                        if (tp.HasNotNullConstraint) constraints.Add("notnull");
                        if (tp.HasUnmanagedTypeConstraint) constraints.Add("unmanaged");
                        constraints.AddRange(tp.ConstraintTypes.Select(ct => ct.ToDisplayString(TypeDisplayFormat)));
                        if (tp.HasConstructorConstraint) constraints.Add("new()");

                        if (constraints.Count > 0)
                            typeParamConstraints.Add($"where {tp.Name} : {string.Join(", ", constraints)}");
                    }

                    var constraintStr = typeParamConstraints.Count > 0
                        ? " " + string.Join(" ", typeParamConstraints)
                        : "";

                    var paramList = new List<string>();
                    var callArgs = new List<string>();

                    foreach (var p in method.Parameters)
                    {
                        var refPrefix = "";
                        var callRefPrefix = "";
                        switch (p.RefKind)
                        {
                            case RefKind.Ref:
                                refPrefix = "ref ";
                                callRefPrefix = "ref ";
                                break;
                            case RefKind.Out:
                                refPrefix = "out ";
                                callRefPrefix = "out ";
                                break;
                            case RefKind.In:
                                refPrefix = "in ";
                                callRefPrefix = "in ";
                                break;
                            case RefKind.RefReadOnlyParameter:
                                refPrefix = "ref readonly ";
                                callRefPrefix = "in ";
                                break;
                        }

                        var isParams = p.IsParams ? "params " : "";
                        var pType = p.Type.ToDisplayString(TypeDisplayFormat);
                        var pName = EscapeIdentifier(p.Name);
                        var defaultVal = p.HasExplicitDefaultValue
                            ? $" = {FormatDefaultValue(p.ExplicitDefaultValue)}"
                            : "";

                        paramList.Add($"{isParams}{refPrefix}{pType} {pName}{defaultVal}");
                        callArgs.Add($"{callRefPrefix}{pName}");
                    }

                    var paramsStr = string.Join(", ", paramList);
                    var callArgsStr = string.Join(", ", callArgs);

                    var methodTypeArgsStr = method.TypeParameters.Length > 0
                        ? $"<{string.Join(", ", method.TypeParameters.Select(p => p.Name))}>"
                        : "";

                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for <see cref=\"{method.Name}\"/></summary>");
                    sb.AppendLine(
                        $"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine(
                        method.ReturnsVoid
                            ? $"{indent}public static void {staticName}{typeParamsStr}({paramsStr}){constraintStr} => Instance.{method.Name}{methodTypeArgsStr}({callArgsStr});"
                            : $"{indent}public static {returnTypeStr} {staticName}{typeParamsStr}({paramsStr}){constraintStr} => Instance.{method.Name}{methodTypeArgsStr}({callArgsStr});");
                    generatedCount++;
                    break;
                }
                case IEventSymbol evt:
                {
                    var typeStr = evt.Type.ToDisplayString(TypeDisplayFormat);
                    sb.AppendLine();
                    sb.AppendLine($"{indent}/// <summary>Static proxy for event <see cref=\"{evt.Name}\"/></summary>");
                    sb.AppendLine($"{indent}public static event {typeStr} {staticName}");
                    sb.AppendLine($"{indent}{{");
                    if (evt.AddMethod is { DeclaredAccessibility: Accessibility.Public })
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    add => Instance.{evt.Name} += value;");
                    }

                    if (evt.RemoveMethod is { DeclaredAccessibility: Accessibility.Public })
                    {
                        sb.AppendLine(
                            $"{indent}    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
                        sb.AppendLine($"{indent}    remove => Instance.{evt.Name} -= value;");
                    }

                    sb.AppendLine($"{indent}}}");
                    generatedCount++;
                    break;
                }
            }
        }
    }

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.IsKeywordKind(SyntaxFacts.GetKeywordKind(name)) ? "@" + name : name;

    private static string FormatDefaultValue(object? value)
    {
        return value switch
        {
            null => "default",
            bool b => b ? "true" : "false",
            string s => $"\"{s.Replace("\"", "\\\"")}\"",
            char c => $"'{c}'",
            float f => $"{f}f",
            double d => $"{d}d",
            decimal m => $"{m}m",
            _ => value.ToString()
        };
    }

    private static bool HasAttribute(ISymbol symbol, string attrName1, string attrName2)
    {
        return Enumerable.Any(symbol.GetAttributes(),
            attr => attr.AttributeClass?.Name == attrName1 || attr.AttributeClass?.Name == attrName2);
    }

    private static string? GetCustomMemberName(ISymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes()
                     .Where(attr => attr.AttributeClass?.Name is "StaticMemberAttribute" or "StaticMember"))
        {
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s1 &&
                !string.IsNullOrEmpty(s1))
                return s1;

            foreach (var namedArg in attr.NamedArguments)
                if (namedArg is { Key: "Name", Value.Value: string s2 } && !string.IsNullOrEmpty(s2))
                    return s2;
        }

        return null;
    }

    private static string GetTypeDeclaration(INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
            return symbol.Name;

        var typeParams = string.Join(", ", symbol.TypeParameters.Select(static p => p.Name));
        return $"{symbol.Name}<{typeParams}>";
    }

    private readonly struct TargetClassInfo(string hintName, string sourceText) : IEquatable<TargetClassInfo>
    {
        public string HintName { get; } = hintName;
        public string SourceText { get; } = sourceText;

        public bool Equals(TargetClassInfo other) => HintName == other.HintName && SourceText == other.SourceText;

        public override bool Equals(object? obj) => obj is TargetClassInfo other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                return HintName.GetHashCode() * 397 ^ SourceText.GetHashCode();
            }
        }
    }
}